var userData = [
    {
        "_id": 1,
        "username": "David",
        "email": "zidane_1080@msn.com",
        "bio": "Add Bio Here!",
        "booksCreated": [],
        "bookContributions": [],
        "followings": [],
        "isVerified": true,
        "isPremium": true,
        "isBanned": false,
        "isModerator": true,
        "upvoteTotal": 3,
        "profilePic": ""
    },
    {
        "_id": 2,
        "username": "John",
        "email": "John@msn.com",
        "bio": "Add Bio Here!",
        "booksCreated": [],
        "bookContributions": [],
        "followings": [],
        "isVerified": true,
        "isPremium": true,
        "isBanned": false,
        "isModerator": true,
        "upvoteTotal": 4,
        "profilePic": ""
    },
    {
        "_id": 3,
        "username": "Elias",
        "email": "Elias@msn.com",
        "bio": "Add Bio Here!",
        "booksCreated": [],
        "bookContributions": [],
        "followings": [],
        "isVerified": true,
        "isPremium": false,
        "isBanned": false,
        "isModerator": false,
        "upvoteTotal": 2,
        "profilePic": ""
    },
    {
        "_id": 4,
        "username": "Alex",
        "email": "alex@msn.com",
        "bio": "Add Bio Here!",
        "booksCreated": [],
        "bookContributions": [],
        "followings": [],
        "isVerified": true,
        "isPremium": false,
        "isBanned": false,
        "isModerator": false,
        "upvoteTotal": 3000,
        "profilePic": ""
    },
    {
        "_id": 5,
        "username": "Joseph",
        "email": "Joe@msn.com",
        "bio": "Add Bio Here!",
        "booksCreated": [],
        "bookContributions": [],
        "followings": [],
        "isVerified": true,
        "isPremium": false,
        "isBanned": false,
        "isModerator": false,
        "upvoteTotal": 252,
        "profilePic": ""
    },
    {
        "_id": 6,
        "username": "Blake",
        "email": "blake@msn.com",
        "bio": "Add Bio Here!",
        "booksCreated": [],
        "bookContributions": [],
        "followings": [],
        "isVerified": false,
        "isPremium": false,
        "isBanned": false,
        "isModerator": false,
        "upvoteTotal": 0,
        "profilePic": ""
    }
]

export default userData